name: sensai
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # basics
  - python=3.7
  - pip
  # optional sensai dependencies for development
  - pytorch=1.4.0
  - tensorflow=1.14.0
  - pyqt=5.12
  - psutil=5.6.7
  - pytorch=1.4.0
  - catboost=0.23
  - xgboost=1.4.0
  - lightgbm=3.1.1
  - utm=0.7.0
  # for notebook support
  - jupyter
  # for tests
  - pytest=5.4.1
  # for release process
  - bump2version
  - pip:
      # non-optional sensai dependencies
      - -r requirements.txt
      # required for locally running the tox build
      - tox
      - virtualenv