name: Python package

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ''
      - name: Merge master into current branch
        run: |
          git fetch origin master:master
          git merge master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`
