name: Merge develop, run tests and build docu

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger the pipeline?
        required: False
        default: Check if it runs again due to external changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # pandoc needed for docu, see https://nbsphinx.readthedocs.io/en/0.7.1/installation.html?highlight=pandoc#pandoc
      - name: Install non-python packages
        run: sudo apt-get update -yq && sudo apt-get -yq install pandoc
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      # lfs=true is not enough, see https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Merge develop into current branch
        run: |
          git fetch origin develop:develop --update-head-ok
          git merge develop
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox # Run tox using the version of Python in `PATH`
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py # don't build docs on py36 due to bugs in sphinx
